version: '3'
services:
  db:
    container_name: pg_container_stock
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - pg-dataset:/var/lib/postgresql/data
  
  pgadmin:
    container_name: pgadmin4_container_stock
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5052:80"

volumes:
  pg-dataset: