require('./api/create-consignment-api');
require('./api/get-all-consigments-api');
require('./api/move-consignment-api');
require('./api/delete-consignment-api');
require('./api/update-consignment-api');
require('./api/move-consignment-api');
require('./api/get-a-consignment-by-id-api');
require('./api/get-filter-data-api')
require('./api/filter-consignments-api');
require('./api/create-bulk-consignment-api');
require('./api/get-consignment-for-location-api');
